name: build and packr2
on:
  push:
    branches: test 

jobs:
  lint:
    name: build 
    runs-on:
      - ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build and push automatic fixes
        run: |
          CI=false cd ./frontend/app && npm i --legacy-peer-deps && npm i --dev-only && npm run build && cd .. && packr2 
          git config user.name 'Github Actions'
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automatic build fixes" || echo -n
          git push

